# Generated by Django 2.2 on 2021-10-08 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
